---
apiVersion: v1
kind: Namespace
metadata:
  name: #{namespace}#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vrt-vivec-svc-cfg
  namespace: #{namespace}#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrt-vivec-svc
  namespace: #{namespace}#
spec:
  replicas: 1  
  minReadySeconds: 10
  selector:
    matchLabels:
      app: vrt-vivec-svc  
  template:
    metadata:
      labels:
        app: vrt-vivec-svc
    spec:
      containers:
      - name: vrt-vivec-svc
        image: acrvrtshared.azurecr.io/vrt.vivec.svc:#{tag}#
        ports:
            - containerPort: 80
        imagePullPolicy: Always
        env:
            - name: Version
              value: #{tag}#
            - name: ASPNETCORE_ENVIRONMENT
              value: #{DeploymentEnvironment}#                    
---
apiVersion: v1
kind: Service
metadata:
  name: vrt-vivec-svc
  namespace: #{namespace}#
spec:
  ports:
    - port: 80
  selector:
    app: vrt-vivec-svc
  type: NodePort
