global using Microsoft.AspNetCore.Mvc;
global using Newtonsoft.Json.Serialization;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Mvc.ApiExplorer;
global using Microsoft.OpenApi.Any;
global using Microsoft.OpenApi.Models;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using FluentValidation;
global using ValidationResult = FluentValidation.Results.ValidationResult;
global using Vrt.Vivec.Svc.Services.Validator;
global using FluentValidation.Results;
global using Vrt.Vivec.Svc.Data.Request;
global using Vrt.Vivec.Svc.Helpers;